### ISSUE TITLE
Namchange erased my score

### ISSUE THREAD

**Issue by AustenJR** [RaiderIO/raiderio-addon#106]
I just changed my character Name and now my score disappeared

**Comment by WFrancois** [comment]
Hey !

Yes, this can occur when changing character name, try to follow these steps :
1. Resync your Blizzard Account to ensure that your characters are claimed (ensure you see your character in your claimed characters list)
2. Go to your character's page and hit Update Now (this may take a while due to queues)

If it still doesn't work, feel free to join raider.io discord (on https://discord.gg/raider) and post in #bug-reports, this will be easier to track down the issue :)
