### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by TheRealSpin** [RaiderIO/raiderio-addon#112]
I have been having issues with people leaving keys lately.  Most of the time it is the people that are playing poorly that are leaving keys.  And I understand that sometimes life happens, but when people rage quit or want to be whiners is not an acceptable reason to waste people's time and brick other people's keys that they work hard for.  I understand that we cannot and should not "punish" people as some of the time it is real issues that come up, however is it possible to add a "left early" counter or something in the io?  As an avid user, I would like to not only see someone's score but see how many completions and walkouts before inviting someone to group because no matter what, I expect the key to be completed.  

Thank you in advance for your time.

**Comment by Vladinator89** [comment]
Hello, it's been a while since you made this suggestion and we have always had this kind suggestion in the back of our heads, but there is no good way to implement something like this, nor would the community really take well to a feature like this, though it would also depend on implementation. We've had some brainstorming sessions but ultimately regardless how something is implemented, there is a large lack of tracking support and we end up with abusable solutions that wouldn't cut it. I am closing this suggestion purely because for the foreseeable future we can't implement something like this reliably.
