### ISSUE TITLE
RaiderIO.HasPlayerProfile nil value

### ISSUE THREAD

**Issue by galaxy119** [RaiderIO/raiderio-addon#140]
Calling the above field results in a lua error that says the field 'HasPlayerProfile' is a nil value.
This just started happening with a recent update in the last day or two, as it worked fine before then.

**Comment by galaxy119** [comment]
RaiderIO.GetPlayerProfile has the same issue.

**Comment by galaxy119** [comment]
Should also be noted - this is only a problem with the version of the addon received from the Raider.IO client, the version on curseforge currently, does not have this issue.

**Comment by Vladinator89** [comment]
Hey! The issue happens because the new RIO addon update changed some things and other addons using RIO might have broken. We did add a hotfix by temporarily adding some code to try bridge the transition, but ultimately it's the other addon and weakaura authors that have to update their code for the future. I'm closing this now since it's been addressed some days ago, but still thanks for your effort to make a ticket. 😊
