### ISSUE TITLE
My M+ Data Is Missing

### ISSUE THREAD

**Issue by Ric0chet-GitHub** [RaiderIO/raiderio-addon#151]
Hello,

I've been running M+ dungeons since they became available to Shadowlands last week, but the Raider.IO tooltip on the Group Finder only shows my Raid Encounters.  No overall Score.  No M+ level breakdowns:
![RaiderIO_Issue](https://user-images.githubusercontent.com/52333533/102367755-1ed04580-3f88-11eb-8432-1f5405b484bb.jpg)
Likewise, the Raider.IO section of my own character frame's tooltip only shows:  
**Raider.IO Raid Progress
CN Normal ______________________  N 4/10**

All appears to be working for other players' characters.  I can see their M+ breakdowns in the Group Finder and M+ data in their character frames' tooltips.

Addon Version: 9.0.2 (v202012160609)
I use the RaiderIO desktop app for updating.  But I also have the Overwolf/CurseForge client (with RaiderIO set to "ignore").
Loaded Americas databases for Horde & Alliance.

I don't think it's strictly an addon issue, but I Deleted the Saved Variable Settings, then Deleted/Reinstalled the Addon, and changed various addon settings (Raid data disables/re-enables correctly).  But after reloading, it still just shows my current Castle Nathria raid data.

I believe this is an Update issue.  During BfA, the addon stopped updating this character's Raid data halfway through Ny'alotha, but continued to update the BfA M+ progress. 

https://raider.io/characters/us/silvermoon/Læthal?utm_source=addon

 I'm out of ideas at this point, thanks.

**Comment by Vladinator89** [comment]
Hello, thanks for the heads-up regarding this issue. We definitely get issues like this where tracking down the issue is not always that simple, sometimes it's an issue with the addon itself but when it's very specific to one person it often is either a sync issue or delay, and it's what it appears to be in your case as well.

For debugging I did get the latest data available from the latest release, then I dumped your data in the game to see what it contains as it helps figure out if the M+ data is there but hidden for some odd reason, or just not there, and it seems to be the later case for you as well.

```
/dump RaiderIO.GetProfile("Læthal", "Silvermoon", 2, "us")

{
  guid = "us 2 Silvermoon Læthal",
  raidProfile = {
    hasRenderableData = true,
    ...
  },
  success = true,
  faction = 2,
  region = "us",
  name = "Læthal",
  realm = "Silvermoon",
}
```

Per right now this was the data I got from your character, the only data is `raidProfile` and there is no `mythicKeystoneProfile` table so it is like you have no M+ data available for your character. I was curious if it would be there but perhaps have the `hasRenderableData` set to `false` or something but it would still be a issue most likely on the data compilation side that for some reason it is having some issue with your character for some odd reason, it doesn't show clearly on this end at least to why this happens.

I will see if someone with access has time to take a look on the data generation side of things to look into the issue, if you are lucky perhaps it's an issue with the previous 200 score limit in place that carried into this season and why many saw no scores appear until they got to 200 and above, I noticed you were just below 200 score and I am curious if you get to 200 or past, if that would magically resolve the issue.

I myself have 0 score in-game but 500 on the website so the issue might be some factor we have not figured out, but I know Jah is working hard on these things right now so it might resolve our issues when he resolves other challenges he is having right now resolving. Often issues are connected and if you fix one you fix multiple other things in cases like these.

**Comment by Ric0chet-GitHub** [comment]
Sure.  Thank you for taking the time to look.   

My current score on the website is 174.  I should have it over 200 by the weekend, but 500 is a couple of weeks off. 

I re-synched my Raider.IO profile with my Blizard account & ensured that this character is still marked as Main in the R.IO interface.  I also queued & scanned our guild, but the raid data looks correct.

**Comment by Vladinator89** [comment]
I might have worded myself poorly, I just compared your and my situation, I have 500 score and I appear in-game with "0" instead of missing M+ data like you experience, but both of us have a similar issue, probably something to do with something deeper into the system and the data generation used by the addon.

I suspect we just need to wait a bit and see what Jah finds out on his end of things as I don't see a clear issue we can resolve ourselves as this point. But it's good to have it documented, it might help narrow down the cause.

**Comment by Ric0chet-GitHub** [comment]
It appears that crossing the 200 threshold solved this.
