### ISSUE TITLE
Weird Icon Appeared

### ISSUE THREAD

**Issue by LordDeimos666** [RaiderIO/raiderio-addon#194]
As the image below, this movable icon appeared, and can't figure out how to remove it.
Provably caused on this commit 0fc9f4e71f7dd46b7970973784a96006fae32655

![immagine](https://user-images.githubusercontent.com/21112906/140056858-0d2f19dd-d30a-46c0-b9a3-370ab922ef5e.png)

**Comment by Vladinator89** [comment]
It looks like the manual tooltip placement anchor for the profiles feature.

I assume since it's visible, that the profiles anchor to that corner and I hope it is draggable since it is visible.

If you open the `/rio` dialog you could see if locking the anchor is on, if you lock it then it should visually go away, but that's the place it would anchor the profile tooltip to in any case.

Hopefully this will help figure out exactly why this appeared for you, by taking a look at the settings regarding the profile anchor.

**Comment by LordDeimos666** [comment]
Problem is not only related to me. As you can see someone else posted on curse about it: https://www.curseforge.com/wow/addons/raiderio?comment=478

Didn't have any problem since some days ago, but locking the frame (that i don't use tbh) solved the "issue". Maybe something related to that commit chanded the behaviour of it, dunno. Worth to mention it for people asking the same question in the next days if someone else has the same problem.

**Comment by Vladinator89** [comment]
I believe that before, we just had the tooltip itself be draggable, so many might have had it unlocked and not noticed, then suddenly after the change added a dedicated anchor frame for dragging, it's noticeable and "odd" when it appears out of nowhere, I agree. I should maybe add some tooltip when you hover it that it's for dragging and you can lock it using `/rio lock` or the dialog option checkbox to "get rid of it" but also anchor it to it. I believe if the positioning is automatic it's by default hidden like it is when locked.

It has not changed for years, so suddenly changing a bit on this makes sense why many might suddenly get surprised where this thing came from. Sorry about that!
