### ISSUE TITLE
Raider io not count for me some runs

### ISSUE THREAD

**Issue by Efkiusz** [RaiderIO/raiderio-addon#55]
Hello, notice yesterday on my main dont have one run from friday and one from saturday. Lucky was doing with friend, but for her its everthing okay. But problem then press on run where we did both there should be my name its showing just retribution paladin(unknow/transfered or renamed).
[https://imgur.com/a/fIRPnnw](url)
https://raider.io/characters/eu/ragnaros/%C3%86valdas my character profile.

**Comment by jahraphael** [comment]
Hi there - best place to open these type of issues would be on the website via the support link (bottom right), or in our Discord in #bug-reports. This is not an issue with the addon.

In general, the problem you are referencing is due to a current issue with the Blizzard API where many characters names are returned as "Unknown". This is something they are aware of and working on a solution for. In the interim, we are trying to find ways to work around it.
