### ISSUE TITLE
BfA : To Do

### ISSUE THREAD

**Issue by WFrancois** [RaiderIO/raiderio-addon#57]
Here's a list of thinks to do / update for the launch of Battle For Azeroth 🎉 

**To update on launch**
- [x] Updates `MAX_LEVEL` to `MAX_PLAYER_LEVEL_TABLE[LE_EXPANSION_BATTLE_FOR_AZEROTH]`
- [x] Support `Legion Score` (can be prepared in advance if I have the time)
- [x] Disable `Average Score for Key Level`

**Can wait mythic plus launch**
- [x] Update `ns.dungeons` in `db_score_tiers.lua`
- [x] Allow translation for the dungeon's short name
- [x] Remove Karazhan exception 🎉 

Starting dungeons : [gist](https://gist.github.com/WFrancois/e485cf5cd5ba36d2df823e1427fb727e)

**Comment by jahraphael** [comment]
Good call on Fortified/Tyrannical affix schedule. Do we even do anything with that right now though?

A few more things you can add:
- Support for "Legion Score". For this I think we should just have a completely separate field that I'll populate from the backend, because I don't think this should be treated like "Best Mythic+ Score". We should show two things during BFA S1: BFA Score, Legion Score (if greater than BFA score). BFA Score should always be given precedence.
- Remove exceptions for Karazhan in code
- Maybe temporarily disable the "Average Score for Key Level", since we won't have any data yet. We can start doing this after the first two weeks of BFA so we have a fortified & tyrannical perhaps?

- To expand on the dungeons stuff, we need to figure out all of the values for DUNGEON_INSTANCEMAPID_TO_DUNGEONID, KEYSTONE_INST_TO_DUNGEONID, LFD_ACTIVITYID_TO_DUNGEONID.

Then there are things from data side:
- Populating new dungeons
- Support for the Legion Score

**Comment by WFrancois** [comment]
No, we don't use the affix schedule (as the difference between the avg score was not major). That's why I edited the comment to remove it.

For the dungeons enum, with the PR adding the Top Guild, this is all going to be in the `dungeons` table. But yeah, I'll try to check what I can find in id.

What do you mean though on data side to populate the new dungeon ?

Adding the rest of your point to my post :)
