### ISSUE TITLE
RaiderIO

### ISSUE THREAD

**Issue by Quietwhisper** [RaiderIO/raiderio-addon#69]
I have just completed a +6 Siege of Boralus in the time and it is not showing up on my raider IO at all. The addon was up and running when I ran it, this is also not the first time it has happened.

**Comment by jahraphael** [comment]
Hi there - the addon doesn't actually record anything. It's simply a view into the data that we have on the website.

As far as the problem you ran into, it is likely due to the second reason on this list: https://raiderio.reamaze.com/kb/current-issues/why-arent-my-recent-runs-showing-up-on-the-site

If you'd like to discuss further, please join our Discord: https://discord.gg/raider
