### ISSUE TITLE
Only works on main character

### ISSUE THREAD

**Issue by supermonteiro** [RaiderIO/raiderio-addon#71]
For w/e reason, the tooltip wont show up on the journal and group finder on my alts. Not even the mouse over tooltip works. It only works on my main.

**Comment by Vladinator89** [comment]
https://support.raider.io/kb/raider-dot-io-mythic-plus-addon/can-i-have-my-mains-score-show-when-on-my-alts

The limit might have been lowered to 250 for BfA since everyone is at lower scores than in Legion right now, but the same system still stands where the alt needs some score to start showing its own score and its main score, as characters included in the dataset have to qualify, otherwise the data would grow too large.
