### ISSUE TITLE
addon size on disk and in memory

### ISSUE THREAD

**Issue by R-Adrian** [RaiderIO/raiderio-addon#78]
As BfA is progressing and more and more characters start showing up in the database, disk space usage and in-game memory usage is starting to get ridiculously high for a single addon, especially with the daily update frequency, so please consider splitting the addon into multiple sub-addons so that users only have to install the data for regions that they're insterested about.

e.g. split the currently built-in secondary addon folders into separate data addons.
- Raider.io Americas - dungeons - alliance
- Raider.io Americas - dungeons - horde
- Raider.io Europe - dungeons - alliance
- Raider.io Europe - dungeons - horde
- Raider.io Asia - dungeons - alliance
- Raider.io Asia - dungeons - horde
- Raider.io Americas - raids - alliance
- Raider.io Americas - raids - horde
- Raider.io Europe - raids - alliance
- Raider.io Europe - raids - horde
- Raider.io Asia - raids - alliance
- Raider.io Asia - raids - horde

this would address the disk space issue, but the memory usage issue still remains... **so, please consider implementing a dynamic user-adjustable high-pass filter so that the interface discards automatically from memory any loaded data about characters with (user-defined) "low" scores?**

(i usually disable TSM and Auctioneer when raiding and in dungeons, but i keep Raider.io active)

![wowscrnshot_110518_212534](https://user-images.githubusercontent.com/16319504/48021855-49f9d100-e142-11e8-94ca-3d01a3606e39.jpg)

**Comment by Petoovee** [comment]
If all players were stored in a table like so
[Realm] = :Name-DataString:Name-DataString:Name-DataString:
Where each realm contained all the players in it
The information for each realm could be compressed with LibCompress
This could potentially reduce the storage and memory size immensely(edited)
However, requesting the data from such a table would come at the expense of unpacking the whole realm and finding the player in it

**Comment by Vladinator89** [comment]
Hello, it's been a while since you suggested improvements on the data storing format and compression. Since then I believe we did overhaul how data is stored by going away from tables and utilizing static strings for the profile data. This did ultimately improve memory a lot compared to having thousands of tables we now have a very large blob string we substr data out from, still using the offset table for lookup.

Since this change I am not sure how to further optimize and save disk space. Luckily static memory plays nice so even if RIO uses 500 MB of memory for the databases it's static and wouldn't affect performance outside a longer loading screen at login or UI /reload. We could always purge unnecessary data after the fact, but it wouldn't help shorten load times in advance.

In that case we would need to perhaps update the RIO Client to download and optimize the data by doing things to it there, before the game loads the databases, but I believe thats a bit out of scope of the project, at least for now.

We try to keep RIO as neutral as possible and just show data, but not add features that do things based on peoples score or try to gauge performance. This is why other people make weakauras and addons to do these things, but we can't really implement a lot of those features into RIO as it would divide the community even more since RIO is already (or was) disliked by many in fear of being another gearscore (and you can say it kind of is) but by not further doing anything with the data outside just showing it like we currently do it's a bit easier to coexist with the whole community and not just one part of it.
